// <auto-generated />
using System;
using AppOscar.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppOscar.Persistence.Migrations.SqlServerMigrations
{
    [DbContext(typeof(AppOscarContextSqlServer))]
    partial class AppOscarContextSqlServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppOscar.Models.Categoria", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoriaPhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FilmeVencedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontosCategoria")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria");

                    b.HasIndex("FilmeVencedorId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AppOscar.Models.Filme", b =>
                {
                    b.Property<Guid>("IdFilme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilmePhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFilme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFilme");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("AppOscar.Models.Participacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFilme")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdFilme");

                    b.ToTable("Participacoes");
                });

            modelBuilder.Entity("AppOscar.Models.User", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senhaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_user");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppOscar.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DthCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdParticipacao")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdParticipacao");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("AppOscar.Models.Categoria", b =>
                {
                    b.HasOne("AppOscar.Models.Filme", "FilmeVencedor")
                        .WithMany("CategoriasVencidas")
                        .HasForeignKey("FilmeVencedorId");
                });

            modelBuilder.Entity("AppOscar.Models.Participacao", b =>
                {
                    b.HasOne("AppOscar.Models.Categoria", "Categoria")
                        .WithMany("Participantes")
                        .HasForeignKey("IdCategoria")
                        .IsRequired();

                    b.HasOne("AppOscar.Models.Filme", "Filme")
                        .WithMany("Participantes")
                        .HasForeignKey("IdFilme")
                        .IsRequired();
                });

            modelBuilder.Entity("AppOscar.Models.Voto", b =>
                {
                    b.HasOne("AppOscar.Models.Participacao", "Participacao")
                        .WithMany("Votos")
                        .HasForeignKey("IdParticipacao")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
